name: 🐛 Bug
description: File a bug / issue
title: "<title>",
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing bug for this issue?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Your configuration
    value: |
        ```bash
        {}
        ```
    render: markdown
  validations:
    required: false