name: Release pacakge

on:
  push:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  # Checkout code & pepare Node JS
  prepare:
    name: Bump Version & Create tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: "Automated Version Update"
        id: version-update
        uses: "phips28/gh-action-bump-version@master"
        with:
          major-wording: "MAJOR,Major"
          minor-wording: "resolve,resolves,resolved,Resolve,Resolves,Resolved,close,closes,closed,Close,Closes,Closed"
          patch-wording: "fix,fixes,fixed,Fix,Fixes,Fixed"
          tag-prefix: "v"
          commit-message: ":bookmark: Set version {{version}}"

    outputs:
      version: ${{ steps.version-update.outputs.newTag }}

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          release_name: ${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: false
